pygments:       true
paginate:       5
permalink:      /:year/:month/:day/:title/

exclude: 
    - README.md

title:          wolfeidau
description:    "Observations and musings of Mark Wolfe, a Linux, Java and Networks guy."

author:
    name:       Mark Wolfe
    email:      mark.wolfe@hsd.com.au
    twitter:    wolfeidau

disqus:
    id:         markwolfesblog

nav:
    - name: Weblog
      url:  /

    - name: About
      url: /about/


copyright: "&copy; Copyright 2011, Mark Wolfe.<br> All Rights Reserved."
